### PR TITLE
Add themes for Acri, Dark and Rachni

### PR DESCRIPTION
**Pull request by DanielRios549**

### CODE REVIEW

**Comment by noeal-dac** [comment]
Thnks Man! It's great! Right now, I don't know why it crash my browser. I think there's a conflict with updating the hotkeys.
I will see how to implement it in the next update.

Sorry if I am not handy with Github protocols. I'm new to all of this (To programming itself).

Thank you very much!

**Comment by DanielRios549** [comment]
Strange, it is working flawlessly in my browser, I didn't change the hotkeys, only things related to theme.

**Comment by noeal-dac** [comment]
Fixed up! It had nothing to do with hotkeys. My suspicions were because, right now, it's a weak point of the code.
The problem with my browser occurred when refreshing the page after choosing a new theme (a strange recursive loop, I think).
I solved it by changing the css without refreshing the page. ¯\_(ツ)_/¯

Thanks for helping!!

**Comment by DanielRios549** [comment]
Really strange, I notice the head tag light up like the code was refreshing but I thought it was because of the hotkeys. Very good to know you fix the problem, accept this pull request and make a fix for the code after that, for the pull request does not keep as open

**Comment by noeal-dac** [comment]
Okey!

**Pull request merged**
